name = input("Enter your name: ")
branch = input("Enter your branch: ")
gender = input("Enter your gender: ")
college= input("Enter your college name: ")
age = int(input("Enter your age: "))
print("Name: ",name)
print("Branch: ",branch)
print("Gender: ",gender)
print("College name: ",college)
print("Age: ",age)